In [30]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [31]:
# Load both sheets from the excel file
df1 = pd.read_excel(r"D:\Restart job hunt\resumes\PROJECT 1\online_retail_II.xlsx",sheet_name="Year 2009-2010")
df2 = pd.read_excel(r"D:\Restart job hunt\resumes\PROJECT 1\online_retail_II.xlsx",sheet_name="Year 2010-2011")

# Combine both sheets into one dataframe
df = pd.concat([df1,df2],ignore_index = True)

print("data loaded successfully")
print("total rows:",len(df))

data loaded successfully
total rows: 1067371

In [32]:
# Look at the first 5 rows 

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [33]:
# Check column names and data types3
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [34]:
# Check missing values in each column
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [35]:
# Remove rows where customer id is missing
df = df.dropna(subset=["Customer ID"])

# Confirm how many rows remains
print("Rows after removing missing Customer IDs:",len(df))

Rows after removing missing Customer IDs: 824364

In [36]:
# Remove rows where description is missing
df = df.dropna(subset=["Description"])

# Confrim how many rows remains
print("Rows after removing missing descriptions:",len(df))

Rows after removing missing descriptions: 824364

In [37]:
# Remove cancelled orders (invoice starting with 'c')
df = df[~df["Invoice"].astype(str).str.startswith("C")]

# Confirm how many rows remain
print("Rows after removing cancelled orders:",len(df))

Rows after removing cancelled orders: 805620

In [38]:
# Checking the -ve values in quantity
print(df["Quantity"].min())

1

In [39]:
#checking the price column if zero or -ve values exists
print(df["Price"].min())

0.0

In [40]:
# count rows where price is zero
print("Zero price rows:",(df["Price"]==0).sum())

Zero price rows: 71

In [41]:
#Removing rows where price is Zero
df = df[df["Price"] > 0]

print("rows after removing zero price:",len(df))

rows after removing zero price: 805549

In [42]:
#fix customer id from float to integer 
df["Customer ID"] = df["Customer ID"].astype(int)

print(df["Customer ID"].dtype)

int32

In [44]:
#Create revenue column
df["Revenue"] = df["Quantity"] * df["Price"]

#check first 5 rows 
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [45]:
#Export clean data to CSV
df.to_csv(r"D:\Restart job hunt\resumes\PROJECT 1\online_retail_clean.csv",index=False)

print("Clean data exported successfully")
print("Final row count:",len(df))

Clean data exported successfully
Final row count: 805549